# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/broker"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/proxy-production"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/proxy"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/sensor-simulation"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/sensor-simulation"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/presence-simulation"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/presence-simulation"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/web-app"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/web-app"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/controller"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/controller"
    schedule:
      interval: "daily"



