version: '3'

services:
  proxy:
    build: proxy
    ports:
      - "80:80"
    environment:
      HOST_NAME:
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - controller
      - web-app
  broker:
    build: broker
    ports:
      - "1883:1883"
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
  influxdb:
    image: influxdb:1.8.0
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      INFLUXDB_DB: data
      INFLUXDB_USER: controller
      INFLUXDB_USER_PASSWORD:
      INFLUXDB_DATA_QUERY_LOG_ENABLED: "false"
      INFLUXDB_HTTP_LOG_ENABLED: "false"
  controller:
    build:
      context: controller
      dockerfile: Dockerfile.jvm
    environment:
      MQTT_HOST: broker
      MQTT_PORT: "1883"
      CONFIG_PATH: /config
      INFLUXDB_USER: controller
      INFLUXDB_USER_PASSWORD:
    volumes:
      - ./rooms.json:/config/rooms.json:ro
      - ./localization.json:/config/localization.json:ro
  temperature-test:
    build: temperature
    environment:
      MQTT_HOST: broker
      ROOM_ID: test
  temperature-office:
    build: temperature
    environment:
      MQTT_HOST: broker
      ROOM_ID: office
  web-app:
    build: web-app


volumes:
  mosquitto-data:
  mosquitto-log:
  influxdb-storage:
