name: CI
on: [ push,pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test controller
      working-directory: controller
      run: mvn test
    - name: Test web-app
      working-directory: web-app
      run: ng build

